# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx1G

# https://fabricmc.net/develop/
# Fabric Properties
minecraft_version=26.1.2
loader_version=0.19.2
loom_version=1.16-SNAPSHOT

# Fabric API
fabric_version=0.146.1+26.1.2

# Mod Properties
mod_version = 1.2.3+26.1.2
maven_group = net.just_s
archives_base_name = survival-debug-mod
