# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx1G

# https://fabricmc.net/develop/
# Fabric Properties
minecraft_version=26.1.2
loader_version=0.19.2

# Fabric API
fabric_version=0.149.1+26.1.2

# Mod Properties
mod_version = 1.2.3+1.21.8
maven_group = net.just_s
archives_name = survival-debug-mod



#loom_version=1.11-SNAPSHOT
